name: prettier
on:
  pull_request:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: NPM - Test, Build, Deploy
      uses: actions/setup-node@v1
      with:
        node-version: 12.11.1

    - name: Cache Yarn Deps
      uses: c-hive/gha-yarn-cache@v1

    - run: yarn install --frozen-lockfile
    - run: yarn prettier:write

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Automated prettier format changes
        branch: ${{ github.head_ref }}
